Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplicationTemplateBase.Filters;

namespace WebApplicationTemplateBase.Controllers
{
    public class HomeController : Controller
    {



        [AutorizarUsuario(nombreMetodo: "-1")]
        public ActionResult Index()
        {
            Models.Usuario Usuario = ((Models.Usuario)Session["Usuario"]);
            Models.MenuIzquierdo MenuIzquierdo = Usuario.Menu;
            ViewBag.menu = MenuIzquierdo.ObtenerMenu();
            ViewBag.userName = Usuario.Rut;
            ViewBag.nombre = Usuario.NombreUsuario;


            return View();
        }


        [AutorizarUsuario(nombreMetodo: "")]
        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }


        [AutorizarUsuario(nombreMetodo: "")]
        public ActionResult Contact()
        {
            Models.Usuario Usuario = ((Models.Usuario)Session["Usuario"]);
            Models.MenuIzquierdo MenuIzquierdo = Usuario.Menu;
            ViewBag.menu = MenuIzquierdo.ObtenerMenu();
            ViewBag.userName = Usuario.Rut;
            ViewBag.nombre = Usuario.NombreUsuario;
            return View();

        }





        [AutorizarUsuario(nombreMetodo: "-1")]
        public ActionResult ErrorPermiso()
        {
            //Dictionary<string, object[]> menu = Models.MenuIzquierdo.ObtenerMenu();
            //ViewBag.menu = menu;
            string nombreUsuario = ((Models.Usuario)Session["Usuario"]).Rut;
            ViewBag.userName = nombreUsuario;
            return View();
        }



        public ActionResult CerrarSesion()
        {
            //Session["Usuario"] = null;
            Session.Abandon();
            return RedirectToAction("Index", "Login");
            
        }




    }
}

Controllers/ReservasController.cs
using Newtonsoft.Json;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Transbank.Common;
using Transbank.Webpay.Common;
using Transbank.Webpay.WebpayPlus;
using WebApplicationTemplateBase.Filters;
using WebApplicationTemplateBase.Models;

namespace WebApplicationTemplateBase.Controllers
{
    public class ReservasController : Controller
    {
        //GET: Reservas
        public ActionResult Index()
        {
            return View();
        }


        [AutorizarUsuario(nombreMetodo: "1")]
        public ActionResult ReservarHora()
        {
            Models.Usuario Usuario = ((Models.Usuario)Session["Usuario"]);
            Models.MenuIzquierdo MenuIzquierdo = Usuario.Menu;
            ViewBag.menu = MenuIzquierdo.ObtenerMenu();
            ViewBag.userName = Usuario.Rut;
            ViewBag.nombre = Usuario.NombreUsuario;
            ///
            ViewBag.dia = DateTime.Now.Day;
            ViewBag.mes = DateTime.Now.Month-1;
            ViewBag.year = DateTime.Now.Year;
            ViewBag.hora = DateTime.Now.Hour;
            //
            return View();
        }


        [AutorizarUsuario(nombreMetodo: "5")]
        public ActionResult PagarMensualidad()
        {
            Models.Usuario Usuario = ((Models.Usuario)Session["Usuario"]);
            Models.MenuIzquierdo MenuIzquierdo = Usuario.Menu;
            ViewBag.menu = MenuIzquierdo.ObtenerMenu();
            ViewBag.userName = Usuario.Rut;
            ViewBag.nombre = Usuario.NombreUsuario;

            return View();
        }


        [HttpPost]
        public JsonResult VerificarSesion()
        {
            int cantidad = Session.Count;
            return Json(new { Correcto = true, JsonRequestBehavior.AllowGet });
        }

        /// <summary>
        /// para reservar hora pagando sola la clase, sin tener pagada la mensualidad
        /// </summary>
        /// <returns></returns>
        public ActionResult ReservarHoraDia()
        {
            ViewBag.menu = new Dictionary<string, Object[]>();
            ViewBag.userName = "Invitado";
            ViewBag.nombre = "Invitado";
            ///
            ViewBag.dia = DateTime.Now.Day;
            ViewBag.mes = DateTime.Now.Month - 1;
            ViewBag.year = DateTime.Now.Year;
            ViewBag.hora = DateTime.Now.Hour;
            //
            return View();
        }


        [AutorizarUsuario(nombreMetodo: "7")]
        public ActionResult MisReservas()
        {
            Models.Usuario Usuario = ((Models.Usuario)Session["Usuario"]);
            Models.MenuIzquierdo MenuIzquierdo = Usuario.Menu;
            ViewBag.menu = MenuIzquierdo.ObtenerMenu();
            ViewBag.userName = Usuario.Rut;
            ViewBag.nombre = Usuario.NombreUsuario;

            return View();
        }


        public ActionResult returnPagarMensualidad(String token_ws, String TBK_ID_SESION, String TBK_ORDEN_COMPRA, String TBK_TOKEN )
        {
            ViewBag.Realizada = false;
            try
            {
                if(token_ws != null)
                {
                    Models.Usuario UsuarioAux = ((Models.Usuario)Session["Usuario"]);
                    Models.Tranferencia Tranferecia = new Models.Tranferencia(token_ws);
                    if (Tranferecia.getResponseCode() == 0)
                    {
                       
                        string rut = UsuarioAux.Rut;
                        string correo = UsuarioAux.Correo;
                       
                        ViewBag.OrdenCompra = Tranferecia.getBuyOrder();
                        ViewBag.Monto = Tranferecia.getMontoFormatoMiles();
                        ViewBag.CodigoAutorizacion = Tranferecia.getAuthorizationCode();
                        ViewBag.FechaTransaccion = Tranferecia.getTransactionDateHorarioChile(4);
                        ViewBag.CantidadCuotas = Tranferecia.getInstallmentsNumber();
                        ViewBag.TipoCuotas = Tranferecia.esCuotas();
                        ViewBag.MontoCuotas = Tranferecia.getInstallmentsAmount();
                        ViewBag.TipoTransaccion = Tranferecia.pasarAFormatoTipoPago();

                        ConsultasExternas.Correos.EnviarCorreoConfirmacionPagoMensualidad(correo, Tranferecia);

                        bool correcto = GuardarTransaccionConfirmada(Tranferecia, rut);
                        int numeroIntentos = 0;
                        if(correcto == false){
                            numeroIntentos = 3;
                        }
                        for (int i = 0; i < numeroIntentos; i++)
                        {
                            correcto = GuardarTransaccionConfirmada(Tranferecia, rut);
                            if (correcto == true){
                                i = numeroIntentos;
                            }
                        }
                        ////****/////
                        

                        if (correcto)
                        {
                            ViewBag.Realizada = true;
                            //ConsultasExternas.Correos.EnviarCorreoConfirmacionPagoMensualidad(correo, Tranferecia);
                        }
                        else
                        {
                            ViewBag.Realizada = false;
                            ViewBag.Detalle = "Transferencia Realizada, pero no registrada en la base de datos, por favor contáctese con la administración";
                        }
                    }
                    else
                    {
                        ViewBag.Realizada = false;
                        ViewBag.Detalle = Tranferecia.getDetalleResponseCode();
                    }
                }
                else
                {
                    if(TBK_TOKEN != null)
                    {
                        ViewBag.Detalle = "Tranferencia Cancelada";
                        Models.Usuario UsuarioAux =  RecuperarSession(TBK_ID_SESION);
                        Session["Usuario"] = UsuarioAux;
                    }
                    else
                    {        
                        ViewBag.Detalle = "Tiempo de Espera Expirado";
                    }
                }

                Models.Usuario Usuario = ((Models.Usuario)Session["Usuario"]);
                Models.MenuIzquierdo MenuIzquierdo = Usuario.Menu;
                ViewBag.menu = MenuIzquierdo.ObtenerMenu();
                ViewBag.userName = Usuario.Rut;
                ViewBag.nombre = Usuario.NombreUsuario;
                return View();
            }
            catch(Exception exp)
            {
                ViewBag.Realizada = false;
                ViewBag.Detalle = exp.Message;
                return View();
            }
        }


        public ActionResult  returnPagarMensualidadClase(String token_ws, String TBK_ID_SESION, String TBK_ORDEN_COMPRA, String TBK_TOKEN)
        {
            ViewBag.Realizada = false;
            try
            {

                if (token_ws != null)
                {
                    Models.Usuario UsuarioAux = ((Models.Usuario)Session["Usuario"]);
                   

                    Models.Tranferencia Tranferecia = new Models.Tranferencia(token_ws);
                    if (Tranferecia.getResponseCode() == 0)
                    {

    
                        string rut = Session["Rut"].ToString();

                        ViewBag.OrdenCompra = Tranferecia.getBuyOrder();
                        ViewBag.Monto = Tranferecia.getMontoFormatoMiles();
                        ViewBag.CodigoAutorizacion = Tranferecia.getAuthorizationCode();
                        ViewBag.FechaTransaccion = Tranferecia.getTransactionDateHorarioChile(4);
                        ViewBag.CantidadCuotas = Tranferecia.getInstallmentsNumber();
                        ViewBag.TipoCuotas = Tranferecia.esCuotas();
                        ViewBag.MontoCuotas = Tranferecia.getInstallmentsAmount();
                        ViewBag.TipoTransaccion = Tranferecia.pasarAFormatoTipoPago();

                        int dia = int.Parse(Session["Dia"].ToString());
                        int mes = int.Parse(Session["Mes"].ToString());
                        int year = int.Parse(Session["Year"].ToString());
                        int idCalendario = int.Parse(Session["IDCalendario"].ToString());
                        string rut_aux = Session["Rut"].ToString();
                        string correo_aux = Session["Correo"].ToString();
                        string nombre_aux = Session["Nombre"].ToString();
                        string fecha = dia + "-" + mes + "-" + year;
                        ConsultasExternas.Correos.EnviarCorreoConfirmacionPagoDia(correo_aux, fecha, idCalendario, Tranferecia);


                        bool correcto = GuardarTransaccionConfirmadaClase(Tranferecia, rut);

                        int numeroIntentos = 0;
                        if (correcto == false)
                        {
                            numeroIntentos = 4;
                        }
                        for (int i = 0; i < numeroIntentos; i++)
                        {
                            correcto = GuardarTransaccionConfirmadaClase(Tranferecia, rut);
                            if (correcto == true)
                            {
                                i = numeroIntentos;
                            }
                        }
                        ////****/////

                        if (correcto)
                        {
                            ViewBag.Realizada = true;
                            /*
                            int dia = int.Parse(Session["Dia"].ToString());
                            int mes = int.Parse(Session["Mes"].ToString());
                            int year = int.Parse(Session["Year"].ToString());

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<link href="~/Scripts/DateRangePicker/daterangepicker.css" rel="stylesheet" />

<div class="container-fluid px-4">
    <h1 class="mt-4">Dashboard</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item active">Dashboard</li>
    </ol>
    <div class="row">

        <input id="calendario_1" type="text" name="daterange" value="" />
        <input id="calendario_2" type="text" name="daterange" value="" />

    </div>

    <script type="text/javascript" src="~/Scripts/jquery-3.6.0.min.js" defer></script>
    <script src="~/Scripts/DateRangePicker/moment.min.js" defer></script>
    <script src="~/Scripts/DateRangePicker/daterangepicker.js" defer></script>
    <script src="~/Scripts/Principal/Calendario.js" defer></script>
</div>

Views/Home/ErrorPermiso.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="es-cl">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>403 Error</title>
    <link href="~/Content/styles.css" rel="stylesheet" />
    <script src="~/Scripts/fontawesome/all.min.js"></script>
</head>
<body>
    <div id="layoutError">
        <div id="layoutError_content">
            <main>
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-lg-6">
                            <div class="text-center mt-4">
                                <img class="mb-4 img-error" src="~/Resources/Asset/error-403-monochrome.jpg" />
                                <p class="lead">No cuenta con los privilegios para acceder!.</p>
                                <a href="@Url.Action("Index","Home")">
                                    <i class="fas fa-arrow-left me-1"></i>
                                    Regresar a Inicio
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </div>
        <div id="layoutError_footer">
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid px-4">

                </div>
            </footer>
        </div>
    </div>
    <script src="~/Scripts/fontawesome/all.min.js"></script>
    <script src="~/Scripts/bootstrap.bundle.min.js"></script>
    <script src="~/Scripts/Principal/scripts.js"></script>
</body>
</html>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<link rel="stylesheet" type="text/css" href="~/Scripts/MenuPrincipal/CuadrosEstilo.css" />



<div id="div_contenido" class="container-fluid px-4 mb-3">
    <div class="row " id="mobil" style="display: none">

        @{
            Dictionary<string, Object[]> menu = ViewBag.menu;

            object[] menuDisponible = menu["Mi Perfil"];


            int i = menuDisponible.Length;

            //
            if (i >= 3)
            {
                <section class="tiles m-0">
                    <article class="style6">
                        <span class="image">
                            <img src="~/Resources/Imagenes/pic01.jpg" alt="" />
                        </span>
                        <a href="@Url.Action("ReservarHora","Reservas")">
                            <h2>Reservar Hora</h2>
                            <div class="content">
                                <p></p>
                            </div>
                        </a>
                    </article>
                    <article class="style4">
                        <span class="image">
                            <img src="~/Resources/Imagenes/pic01.jpg" alt="" />
                        </span>
                        <a href="@Url.Action("ReservarInstalacion","ReservasInstalacion")">
                            <h2>Reservar Instalación</h2>
                            <div class="content">
                                <p></p>
                            </div>
                        </a>
                    </article>
                    <article class="style2">
                        <span class="image">
                            <img src="~/Resources/Imagenes/pic01.jpg" alt="" />
                        </span>
                        <a href="@Url.Action("MisReservas","Reservas")">
                            <h2>Mis Reservas</h2>
                            <div class="content">
                                <p></p>
                            </div>
                        </a>
                    </article>
                    <article class="style3">
                        <span class="image">
                            <img src="~/Resources/Imagenes/pic01.jpg" alt="" />
                        </span>
                        <a href="@Url.Action("PagarMensualidad","Reservas")">
                            <h2>Pagar Mensualidad</h2>
                            <div class="content">
                                <p></p>
                            </div>
                        </a>
                    </article>
                </section>
            }
            else
            {
                <section class="tiles m-0">
                    <article class="style4">
                        <span class="image">
                            <img src="~/Resources/Imagenes/pic01.jpg" alt="" />
                        </span>
                        <a href="@Url.Action("ReservarInstalacion","ReservasInstalacion")">
                            <h2>Reservar Instalación</h2>
                            <div class="content">
                                <p></p>
                            </div>
                        </a>
                    </article>
                </section>
            }

        }




    </div>
    <div class="row " id="pcs" >
        
    </div>
</div>

<script type="text/javascript" src="~/Scripts/jquery-3.6.0.min.js" defer></script>
<script type="text/javascript" src="~/Scripts/Principal/Sistema/Home/Index.js" defer></script>